services:
  couchdb:
    image: couchdb:3.4.2
    container_name: db
    restart: unless-stopped
    ports:
      - '127.0.0.1:5984:5984'
      - '127.0.0.1:4369:4369'
      - '127.0.0.1:9100:9100'
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
  casinodb:
    depends_on:
      - couchdb
    build: .
    image: casinodb
    container_name: casinodb
    restart: unless-stopped
    network_mode: 'host'
    # ports:
    #   - '127.0.0.1:3000:3000'
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - MNEMONIC=${MNEMONIC}
      - TREASURY_ADDRESS=${TREASURY_ADDRESS}
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
