services:
  api:
    build: .
    image: api
    container_name: api
    restart: unless-stopped
    network_mode: 'host'
    # ports:
      # - '127.0.0.1:4000:3000'
    environment:
      - HOST=${HOST}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
# networks:
#   myapp-network:
#     driver: bridge
